### ISSUE TITLE
Some class I can't find

### ISSUE THREAD

**Issue by lvxingtu** [Gleidson28/DashboardFx#1]
com.gn.control.DrawerContent
com.gn.control.DrawerList
and so on.

**Comment by lvxingtu** [comment]
Hello

**Comment by Gleidson28** [comment]
Hello, I'm splitting the drawer project, here's a link, I'm going to add a beta jar, but incomplete .. I'm still implementing the children for the component..

https://github.com/Gleidson28/GNDrawer

**Comment by lvxingtu** [comment]
How did you make it ? I mean the beautil ui with JavaFx
How make it so awesome?

**Comment by Gleidson28** [comment]
Thanks, Build this ui is my hobby...

**Comment by lvxingtu** [comment]
Hello, I am interested in beautiful ui too.But I don't have the ability to achieve it.
So could you teach me a little tips？ 
Thank you very much
