### ISSUE TITLE
Unable To Execute the project

### ISSUE THREAD

**Issue by AkshaySinghR** [Gleidson28/DashboardFx#20]
Imported Project into IDEA and imported library. But Couldn't execute

**Comment by Gleidson28** [comment]
Hi, ok... the dependencies are in lib folder... all dependencies... today I checked... and pushed my local folder... in my machine, I use java 1.8.0_181 ... please describe more about your problem.

**Comment by CarlosTTRR** [comment]
I ran this project creating a new Java / maven project in Eclipse (It can be your IDE) and the SRC folder copied it, as well as the libraries, in this way I could run it without problems

**Comment by intothesea** [comment]
It seems that Scene Builder can't open some .fxml files in this project ,eg. Carousel.fxml. I found that this seems to be due to the fact that scene builder does not recognize the components in GNCarousel. Please tell me how you solved this problem.
