### ISSUE TITLE
Error class TextFieldSkin

### ISSUE THREAD

**Issue by biazinha21** [Gleidson28/DashboardFx#21]
Hello, I am trying to build the project in IDEA, but couldn't execute.

![error](https://user-images.githubusercontent.com/18722830/52733493-01a44780-2faa-11e9-9d2a-40aad49dff63.PNG)

**Comment by Gleidson28** [comment]
Hi, ok show me your jdk version, TextField skin, may have been moved in its version.. 
I can change for you

**Comment by biazinha21** [comment]
My jdk is 11.0.2

**Comment by Gleidson28** [comment]
Hi, I'm going to create a branch with the version, I was even wanting to go to version 11, regards, thanks

**Comment by janithaDassanayake** [comment]
can i run this one from the netbeans sir

**Comment by Gleidson28** [comment]
Yes, configure dependencies using the lib folder, it is simple. regards

**Comment by micheal914** [comment]
I could not build this DashbordFX on Apache Netbeans IDE 11.2.
My java version is 1.8.0_181.
Please know me your JDK version.

**Comment by Gleidson28** [comment]
My version is that..

**Comment by Chuntianhong** [comment]
I also couldn't compile with the same issue.


import com.sun.javafx.scene.control.skin.TextFieldSkin;

This give me an error.
Is there any other solution?
